### ISSUE TITLE
Nested nodes group issue

### ISSUE THREAD

**Issue by kasperski95** [bdancer/blender-for-vray#171]
The issue occurs when a node group is inside another node group.

![issue](https://cloud.githubusercontent.com/assets/9629577/16048020/ca18f9b6-3252-11e6-8e44-237d6a7c3710.jpg)

**Comment by bdancer** [comment]
Fixed with: https://github.com/bdancer/blender-for-vray/commit/8141c15197958efc4f53a7f3ff0c1c35e6b8d9bc

**Comment by kasperski95** [comment]
Thanks

**Comment by kasperski95** [comment]
Problem still occurs, if node `2` is linked to a blend file.

**Comment by kasperski95** [comment]
Nevermind, build 8141c15 from 20160622 actually is a 842478a.
